### PR TITLE
Update URL for assets from Google repository

### PR DESCRIPTION
**Pull request by celcius-jochen**
The original Google repository has moved to another location.

### CODE REVIEW

**Comment by bradcornford** [comment]
Thanks for this. Will get this merged now.

**Comment by cornerstonesoftware** [comment]
I updated to version 2.35.1. 
I see the source files have changed to googlearchive but when i load the page it seems like its still trying to fetch the old url (http://googlemaps.github.io/js-marker-clusterer/src/markerclusterer.js) 

What am i missing?

**Comment by celcius-jochen** [comment]
Check your published view & config:

- `resources\views\cornford\googlmapper\javascript.blade.php`
- `config\googlmapper.php`

**Comment by cornerstonesoftware** [comment]
Thank you for your fast response, this was the problem.
I tried the following command to update the view:
php artisan vendor:publish --provider="Cornford\Googlmapper\MapperServiceProvider" --tag=googlmapper

Output:
Copied Directory [/vendor/cornford/googlmapper/src/views] To [/resources/views/cornford/googlmapper]
Publishing complete.

But nothing changed. After i deleted the folder cornford in resources/views and tried the command again it worked without a problem.

Is there a command to replace the files without deleting them manually?

**Comment by celcius-jochen** [comment]
Yes there is, add `--force` at the end of your artisan command.

```
php artisan help vendor:publish

Description:
  Publish any publishable assets from vendor packages

Usage:
  vendor:publish [options]

Options:
      --force                Overwrite any existing files
      --all                  Publish assets for all service providers without prompt
      --provider[=PROVIDER]  The service provider that has assets you want to publish
      --tag[=TAG]            One or many tags that have assets you want to publish (multiple values allowed)
  -h, --help                 Display this help message
  -q, --quiet                Do not output any message
  -V, --version              Display this application version
      --ansi                 Force ANSI output
      --no-ansi              Disable ANSI output
  -n, --no-interaction       Do not ask any interactive question
      --env[=ENV]            The environment the command should run under
  -v|vv|vvv, --verbose       Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug
```

**Pull request merged**
