### PR TITLE
Ajax request

### PR DESCRIPTION
**Pull request by m7vm7v**
Hi, Is it possible to create some kind of ajax request. For example if we have huge points to show we will show the first 100 for example and the rest will be with ajax. Thanks mate.
Your work is wonderfull.

### CODE REVIEW

**Comment by bradcornford** [comment]
Hi, Yeah it would be possible, however it a little out of the range of what GooglMapper does. However, some script could be used to do this:

```js
jQuery.ajax({
	url : '/data/markers',
	dataType : 'json',
	success : function(response) {		
		if (response.status == 'OK') {
			markers = response.markers;

			// Loop through markers and add them to the map
			for (item in markers) {
				// Create google map lat and long
				tmpLatLng = new google.maps.LatLng(markers[item].geo[0], markers[item].geo[1]);

				// Make and place map maker
				var marker = new google.maps.Marker({
				    map: map,
				    position: tmpLatLng,
				    title : markers[item].name + "<br>" + markers[item].geo_name
				});

				// Create an information window
				google.maps.event.addListener(marker, 'click', function(markers, item) {
			        infowindow.setContent('<b>' + markers[item].name + "</b><br>" + markers[item].geo_name);
			        infowindow.open(map, marker);
			    });
			}
		}
	}
});
```

**Comment by m7vm7v** [comment]
Hi, can you give some more help how to build it all together.
My type route is POST and it leads to controller:
$query = e(Input::get('q',''));

            //if(!$query && $query == '') return response()->json(array(), 400);

            $products = Wells::where('well_name','like','%'.$query.'%')
                    ->orderBy('well_name','asc')
                    ->take(5)
                    ->select('well_id','well_name', 'longitude', 'latitude')
                    ->get()->toArray();            
            return response()->json(array('data'=>$products));

my controller that leads to the view looks like:

        $wells = DB::table('wells')->select('longitude', 'latitude', 'well_id')->where('iso3_code', '=', 'USA')->take(100)->get();    
        $map = Mapper::map(2,4);        
        foreach ($wells as $well) {
            $map->informationWindow($well->latitude, $well->longitude, '<a href="/well/'. $well->well_id .'">Link</a>');
        }
	return view('else/json');

and the js is the same as your's

**Comment by bradcornford** [comment]
Hi, what is the format of the data returned from return response()->json(array('data'=>$products));?

**Comment by bradcornford** [comment]
Also whats the source of /js/search/searchJson.js?

**Comment by m7vm7v** [comment]
What exactly do you mean... it is array. And the output looks something like:

{"data":[{"well_id":19620,"long":2.45085,"lat":56.9479},{"well_id":13753,"long":2.98015,"lat":56.9517},{"well_id":15430,"long":2.66994,"lat":56.9313},{"well_id":15432,"long":2.95722,"lat":56.9822},{"well_id":19623,"long":2.82587,"lat":56.7519}]}

and /js/search/searchJson.js 

$(document).ready(function(){
    $.ajaxSetup({
	headers: {
		'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
	        }
    });
    jQuery.ajax({
    url : '/dashboard/jsons',
    type: 'POST',
    dataType : 'json',
    success : function(response) {      
        if (response.status == 'OK') {
            markers = response.markers;

            // Loop through markers and add them to the map
            for (item in markers) {

                // Create google map lat and long
                tmpLatLng = new google.maps.LatLng(markers[item].geo[0], markers[item].geo[1]);

                // Make and place map maker
                var marker = new google.maps.Marker({
                    map: map,
                    position: tmpLatLng,
                    title : markers[item].name + "<br>" + markers[item].geo_name
                });

                // Create an information window
                google.maps.event.addListener(marker, 'click', function(markers, item) {
                    infowindow.setContent('<b>' + markers[item].name + "</b><br>" + markers[item].geo_name);
                    infowindow.open(map, marker);
                });
            }
        }
    }
	});
});

**Comment by bradcornford** [comment]
Okay, i've quickly thrown something together in my routes.php so you would have to split it out etc, however the logic seems valid:

``` php

Route::get('/', function()
{

    Mapper::map(2, 4, ['marker' => false]);

    print Mapper::render();

    print "
<script type='text/javascript' src='https://code.jquery.com/jquery-1.12.0.min.js'></script>
<script type='text/javascript'>

$(document).ready(function() {
    var infowindow =  new google.maps.InfoWindow({
        content: ''
    });

    var marker =  new google.maps.Marker({
        title: ''
    });

    jQuery.ajax({
        url : window.location.href + '/data/markers',
        dataType : 'json',
        success : function(response) {
            if (response.wells) {
                markers = response.wells;

                for (item in markers) {
                    var marker = new google.maps.Marker({
                        map: maps[0].map,
                        position: new google.maps.LatLng(markers[item].lat, markers[item].long)
                    });

                    bindInfowindow(marker, maps[0].map, infowindow,  '<a href=\"/well/' + markers[item].well_id + '\">Link</a>');
                }
            }
        }
    });

    var bindInfowindow = function(marker, map, infowindow, html) {
        google.maps.event.addListener(marker, 'click', function() {
            infowindow.setContent(html);
            infowindow.open(map, marker);
        });
    }
});

</script>";

});

Route::get('/data/markers', function()
{
    $data = array(
        array(
            'well_id' => 19620,
            'long' => 2.45085,
            'lat' => 56.9479,
        ),
        array(
            'well_id' => 13753,
            'long' => 2.98015,
            'lat' => 56.9517,
        ),
        array(
            'well_id' => 15430,
            'long' => 2.66994,
            'lat' => 56.9313,
        ),
        array(
            'well_id' => 15432,
            'long' => 2.95722,
            'lat' => 56.9822,
        )
    );

    return response()->json(array('wells'=>$data));
});

```

**Comment by m7vm7v** [comment]
I have Uncaught TypeError: Cannot read property 'map' of undefined

**Comment by bradcornford** [comment]
Try adding console.log(maps[0].map); within the for loop

**Comment by m7vm7v** [comment]
for console.log(markers[item].long); I have right result 
for console.log(maps[0].map);  Uncaught TypeError: Cannot read property 'map' of undefined

**Comment by bradcornford** [comment]
Try:

```
console.log(maps); 
```

**Comment by m7vm7v** [comment]
for (item in markers) {
     (line 18)console.log(maps); 
                  var marker = new google.maps.Marker({
                        (line 20)map: maps[0].map,
                        position: new google.maps.LatLng(markers[item].lat, markers[item].long)
                    });
                    bindInfowindow(marker, maps[0].map, infowindow,  '<a href=\"/well/' + markers[item].well_id + '\">Link</a>');
                }



for line 18 is empty array []
for line 20 is the known error Uncaught TypeError: Cannot read property 'map' of undefined

**Comment by bradcornford** [comment]
Are you rendering a map to the view?

**Comment by m7vm7v** [comment]
yep. it is exactly I have said in the 3rd comment here

**Comment by bradcornford** [comment]
Move the script to after the render.

**Comment by m7vm7v** [comment]
Yea, ihave tried it but it is the same... I have put tge script to the bottom and the message is syill there

**Comment by bradcornford** [comment]
Can you send me the html source.

**Comment by m7vm7v** [comment]
<script type="text/javascript" src='/js/search/searchJson.js'></script>
<meta name="csrf-token" content="{{ csrf_token() }}" />
<div class="input-group custom-search-form">
    <input id="searchbox" name="q" type="text" class="form-control" placeholder="Search...">
    <input name="_token" value="{{ csrf_token() }}" type="hidden">
</div> 
<div style="width: 100%; height: 600px;">{!! Mapper::render() !


And i have tried with the script on the bottom but it is the same error

**Comment by bradcornford** [comment]
Have you added jQuery as a script dependency?

```html
<script type='text/javascript' src='https://code.jquery.com/jquery-1.12.0.min.js'></script>
```

**Comment by m7vm7v** [comment]
Yep it is added in the master.layout included in this blade

**Comment by bradcornford** [comment]
Can you send me the html source from the browser?

**Comment by m7vm7v** [comment]
it is 5k lines ....

**Comment by bradcornford** [comment]
Okay, I believe it may be that the map isn't loading in time for the fire event of document ready by jQuery.

Try this:

```js

maps[0].map.addEventListener('google-map-ready', function(e) {
   $.ajaxSetup({
        headers: {
            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
        }
    });
    
    jQuery.ajax({
        url : '/dashboard/jsons',
        type: 'POST',
        dataType : 'json',
        success : function(response) {      
            if (response.status == 'OK') {
                markers = response.markers;

                // Loop through markers and add them to the map
                for (item in markers) {

                    // Create google map lat and long
                    tmpLatLng = new google.maps.LatLng(markers[item].geo[0], markers[item].geo[1]);

                    // Make and place map maker
                    var marker = new google.maps.Marker({
                        map: map,
                        position: tmpLatLng,
                        title : markers[item].name + "<br>" + markers[item].geo_name
                    });

                    // Create an information window
                    google.maps.event.addListener(marker, 'click', function(markers, item) {
                        infowindow.setContent('<b>' + markers[item].name + "</b><br>" + markers[item].geo_name);
                        infowindow.open(map, marker);
                    });
                }
            }
        }
    });
});

```

**Comment by m7vm7v** [comment]
Still the same

**Comment by bradcornford** [comment]
Can you limit your map creation to 10 items, and see if you get the same error.

**Comment by m7vm7v** [comment]
Same error

**Comment by bradcornford** [comment]
You'll need to send me the JS for the map to investigate.

**Comment by m7vm7v** [comment]
give me your skype or some other way so it is better ...so we wont spam so much in here... after that we will post the solution in here if there is someone else who needs this

**Comment by bradcornford** [comment]
My email is bradcornford (at) hotmail (dot) co (dot) uk

**Comment by m7vm7v** [comment]
In the end the searchJason.js needs to load a little bit later:

setTimeout(function () {
        loadMapData();
    }, 1000);

**Comment by bradcornford** [comment]
Hi,

I've added events for map loading. See the develop branch:

```php
	Mapper::map(53.381128999999990000, -1.470085000000040000, ['eventBeforeLoad' => 'console.log("before load");']);


	Mapper::map(53.381128999999990000, -1.470085000000040000, ['eventAfterLoad' => 'console.log("after load");']);
```

**Comment by m7vm7v** [comment]
It is strange how the new data is not added to the cluster data ....even if zoom in or out it it will never be added to the cluster ... I don't know is that can be considered as a bug or ...

**Comment by bradcornford** [comment]
You would probably have to disable marker clusters, and then introduce them yourself once all markers are loaded for the map:

Add this to you AJAX load for loop:
```js
maps[0].markers.push(marker);
```

Add this after your AJAX load:
```js
var markerCluster = new MarkerClusterer(maps[0].map, maps[0].markers);
```

**Pull request closed without merging**
