### PR TITLE
dragend_event marker

### PR DESCRIPTION
**Pull request by eskrano**
Hi ! I am add option for draggend event in markers. See changed files.

### CODE REVIEW

**Comment by bradcornford** [comment]
Hi again, can you make sure your master branch is up to date, then rebase your work on top. As i have made some changes to the branch itself, and your this merge request contains your previous work too.

**Comment by eskrano** [comment]
How can I do it? I just do not understand much else.

**Comment by bradcornford** [comment]
You should be able to do:

```
git fetch origin
git rebase origin/master
```

**Comment by eskrano** [comment]
I can't becouse i'am noob with git (http://prntscr.com/9noyt4) :D can you add my commits to master repo? I am need this feature for my project ...

**Comment by bradcornford** [comment]
Yeah sure, i'll add them today.

**Comment by bradcornford** [comment]
I've now added this to develop if you want to check it out.

**Comment by bradcornford** [comment]
I have now added this to current version 2.6.0.

**Pull request closed without merging**
