### PR TITLE
Creating a 3d buildings

### PR DESCRIPTION
**Pull request by m7vm7v**
Is it possible to create a 3d objects if not can you please help me how to build some.

### CODE REVIEW

**Comment by bradcornford** [comment]
I don't believe 3D buildings are show in the JavaScript API for Google Maps.

**Comment by m7vm7v** [comment]
is there any king of aproach to create 3d building. I have seen that is possible to be created  a polygone on the bulding and a second one with the same points but a bit higher then the original (the roof) and then to connect both of the polygones to create the walls... Is it possible to make such an algorytm to run this idea. Or it would be better if I use other source (not google dev) for this one.
 Thanks for your work.

**Comment by bradcornford** [comment]
That would be possible, but i believe it would be fairly complex. You could take a look into the following:

http://johndyer.name/drawing-3d-objects-and-building-on-google-maps/

It looks like you have to create polygons around the building then utilise the drawExcrudedShape method to create walls / roofs. However you would still need to manually create the polgon shapes around buildings manually.

**Comment by m7vm7v** [comment]
I think I have manage to create something usefull : 

Mapper.php
`/**
     * Add a new map 3d building.
     *
     * @param array $coordinates
     * @param array $bottomOptions
     * @param array $topOptions
     * @param array $wallsOptions
     * @param array $height
     *
     * @return self
     */
    public function building(array $coordinates = [], array $bottomOptions = [], array $topOptions = [], array $wallsOptions = [], $height = 0.1) {
        
        $i = 0;
        foreach($coordinates as $coord){
            $bottom[$i]['latitude'] = $coord['latitude'];
            $bottom[$i]['longitude'] = $coord['longitude'];
            
            $top[$i]['latitude'] = $coord['latitude'] + $height;
            $top[$i]['longitude'] = $coord['longitude'] + $height;
            
            $i++;
        }
        $i--;
        
        //bottom
        $this->polygon($bottom, $bottomOptions);
        
        //roof
        $this->polygon($top, $topOptions);
        
        //walls
        for($w = $i; $w >= 0; $w--){
            $z= $w - 1;
            if($w === 0) $z = $i;
            $this->polygon([$bottom[$w], $bottom[$z], $top[$z], $top[$w]], $wallsOptions);
        }
        
        return $this;
    }`

and the example for it :

`Mapper::map(1, 1, ['zoom' => 8, 'center' => true]);
        
        $coordinates = [['latitude' => 1, 'longitude' => 1], ['latitude' => 3, 'longitude' => 1], ['latitude' => 3, 'longitude' => 3], ['latitude' => 1, 'longitude' => 3], ['latitude' => 0, 'longitude' => 1.2], ['latitude' => 0.5, 'longitude' => 1.5]];
        $bottomOptions = ['fillColor' => 'red', 'strokeColor' => 'red', 'strokeOpacity' => 0.5];
        $topOptions = ['fillColor' => 'blue', 'strokeColor' => 'blue', 'strokeWeight' => 5, 'strokeOpacity' => 1, 'fillOpacity' => 1];
        $wallsOptions = ['fillColor' => 'yellow', 'strokeColor' => 'yellow', 'strokeOpacity' => 0.1];
        $height = 0.5;
                
        Mapper::building($coordinates, $bottomOptions, $topOptions, $wallsOptions, $height);`


It might need some refactoring and meaby I am missing something but if that is helpful for someone I will be happy.

**Comment by bradcornford** [comment]
Looks complicated at a glance! I'll take a proper look later/

**Comment by bradcornford** [comment]
Ive raised an issue for this: https://github.com/bradcornford/Googlmapper/issues/71

**Pull request closed without merging**
