### PR TITLE
Add option for draggable markers

### PR DESCRIPTION
**Pull request by eskrano**

### CODE REVIEW

**Comment by bradcornford** [comment]
Any chance you can update the README.md under the configuration section for this change?

**Comment by eskrano** [comment]
When will update the readme, you accept the pull request?

**Comment by bradcornford** [comment]
Yeah, sorry I did mean to mention seems a good idea to me! Only thing I could see is that some markers may want to be dragable, however some don't too. Yeah, once that is updated, I'd happily merge and version this.

**Comment by eskrano** [comment]
Im update readme, you can accept pull request. In few time im proposed other pull requests.

**Comment by bradcornford** [comment]
Great, thanks for this!

**Comment by bradcornford** [comment]
This has now been versioned into current version 2.4.0.

**Comment by eskrano** [comment]
ok .

**Pull request merged**
